server:
  port: 8000
  ssl:
    key-store: classpath:time7.top.jks
    key-store-password: nkrn2pusx3vb
    key-store-type: JKS

spring:
  datasource:
    url: jdbc:mysql://119.91.22.108:3306/tm_blog?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: "Hanhan0317"
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 119.91.22.108
    port: 6379
    password: 123456
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-request-size: 10MB
  # 后端传入前端，时间少了8个小时
  jackson:
    time-zone: GMT+8
  minio:
    endpoint: https://time7.top:9000
    bucketName: blog
    accessKey: minioadmin
    secretKey: minioadmin
  # 发送邮件
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.163.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 15971080935@163.com
    #授权码
    password: THEQUKWIFZIUZRHJ
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    expire: 600

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true