server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tm_blog?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: "12345678"
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-request-size: 10MB
  # 后端传入前端，时间少了8个小时
  jackson:
    time-zone: GMT+8
  minio:
    endpoint: http://119.91.22.108:9000
    bucketName: blog
    accessKey: minioadmin
    secretKey: minioadmin

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true